version: '3.8'

services:
  web:
    # Define the build context for the Docker image
    build: .
    # Set the name for the container
    container_name: flowerbed_api
    # Expose the port
    ports:
      - "8000:8000"
    # Load environment variables from a file
    env_file:
      - .env
    # Mount volumes for data persistence
    volumes:
      - .:/app
    # Restart the container if it crashes
    restart: always

  worker:
      build: .
      container_name: flowerbed_scheduler_worker
      # Overwrites the default CMD statement inside Dockerfile to target our scheduler instead
      command: python scheduler.py
      env_file:
        - .env
      volumes:
        - .:/app
      restart: always
